url: https://y7kim.github.io
baseurl: /indievisible

# Site settings
title: IndieVisible
email: programad@gmail.com
description: "The independent developers community. Nothing can divide us! (by zero?)"


# Team names, titles and social links
people:
- name: Daniel Gomes
  pic: danielgomes
  position: Founder
  social:
    - title: twitter
      url: https://www.twitter.com/programad
    - title: facebook
      url: https://www.facebook.com/programad

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/indievisiblenet
  - title: github
    url: https://github.com/anteatergames/indievisible

# Postal address (add as many lines as necessary)
address:
  - line: Santos/Brazil

# Build settings
markdown: kramdown
permalink: pretty